name: Run ESLint

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '>=21.1.0'
      - name: Install ESLint dependencies
        run: |
          npm install @eslint/eslintrc
          npm install @faker-js/faker        
      - name: Run ESLint
        run: npm run lint