name: Run ESLint

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '>=16.0.0'
      - name: Install ESLint dependencies
        run: npm install @eslint/eslintrc
      - name: Install Faker js library
        run: npm install @faker-js/faker        
      - name: Run ESLint
        uses: stefanoeb/eslint-action@1.0.2
        with:
          files: .
