name: Run ESLint

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js Dependencies
        run: |
          npm install
      - name: Run ESLint
        uses: stefanoeb/eslint-action@1.0.2
        with:
          files: .
