name: Run ESLint

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '>=21.1.0'
      - name: Install ESLint and Prettier dependencies
        run: |
          npm install @eslint/eslintrc @faker-js/faker --save-dev
          npm install --save-dev prettier
      - name: Run ESLint and Prettier
        run: npm run lint && npx prettier . --check