name: Playwright Tests - My Learning Path

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    # Run tests on a daily basis at 9:30 AM UTC
    - cron: "30 9 * * *"

jobs:
  cache:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.9.0
          check-latest: false

      - name: Cache Playwright dependencies
        id: playwright-cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/playwright
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

  test:
    needs: cache
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.9.0
          check-latest: false

      - name: Restore Playwright cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/playwright
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload Playwright report
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
